language: java
env:
  global:
    - GRADLE_HOME="$PWD/gradle-7.4"
    - PATH=$GRADLE_HOME/bin:$PATH
install: skip
before_script:
  - wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
  - unzip -qq gradle-7.4.2-bin.zip
script:
  - ./gradlew run

jobs:
  include:
    - jdk: openjdk8
      dist: trusty
    - jdk: openjdk11
      dist: trusty
    - jdk: openjdk15
      dist: trusty
    - jdk: openjdk8
      dist: xenial
    - jdk: openjdk11
      dist: xenial
    - jdk: openjdk15
      dist: xenial
    - jdk: openjdk8
      dist: bionic
    - jdk: openjdk11
      dist: bionic
    - jdk: openjdk15
      dist: bionic
    - jdk: openjdk8
      dist: focal
    - jdk: openjdk11
      dist: focal
    - jdk: openjdk15
      dist: focal
      
      
